import {
  RenderBlockquote,
  RenderBr,
  RenderCheckbox,
  RenderCode,
  RenderCodeSpan,
  RenderDef,
  RenderDel,
  RenderEm,
  RenderEscape,
  RenderHeading,
  RenderHr,
  RenderHtml,
  RenderImage,
  RenderLink,
  RenderList,
  RenderListItem,
  RenderParagraph,
  RenderRawTable,
  RenderReactElement,
  RenderSpace,
  RenderStrong,
  RenderTable,
  RenderTableCell,
  RenderTableRow,
  RenderTableSection,
  RenderTag,
  RenderTask,
  RenderText,
} from "./renderers/index.js";
import { type MarkdownRenderers } from "./types.js";

export const DEFAULT_MARKDOWN_RENDERERS = {
  hr: RenderHr,
  br: RenderBr,
  def: RenderDef,
  space: RenderSpace,
  escape: RenderEscape,

  text: RenderText,
  em: RenderEm,
  del: RenderDel,
  strong: RenderStrong,
  heading: RenderHeading,
  paragraph: RenderParagraph,
  blockquote: RenderBlockquote,

  link: RenderLink,

  code: RenderCode,
  codespan: RenderCodeSpan,

  image: RenderImage,

  checkbox: RenderCheckbox,
  list: RenderList,
  listitem: RenderListItem,
  task: RenderTask,

  raw_table: RenderRawTable,
  table: RenderTable,
  tablecell: RenderTableCell,
  tablerow: RenderTableRow,
  thead: RenderTableSection,
  tbody: RenderTableSection,

  react: RenderReactElement,
  html: RenderHtml,
  tag: RenderTag,
} satisfies MarkdownRenderers;
