import {
  RenderBlockquote,
  RenderBr,
  RenderCheckbox,
  RenderCode,
  RenderCodeSpan,
  RenderDef,
  RenderDel,
  RenderEm,
  RenderEscape,
  RenderGeneric,
  RenderHeading,
  RenderHr,
  RenderHtml,
  RenderImage,
  RenderLink,
  RenderList,
  RenderListItem,
  RenderParagraph,
  RenderSpace,
  RenderStrong,
  RenderTable,
  RenderTableCell,
  RenderTableSection,
  RenderTag,
  RenderTask,
  RenderText,
  RenderTr,
} from "./renderers/index.js";
import { type MarkdownRenderers } from "./types.js";

export const DEFAULT_MARKDOWN_RENDERERS = {
  hr: RenderHr,
  br: RenderBr,
  def: RenderDef,
  del: RenderDel,
  space: RenderSpace,
  escape: RenderEscape,
  strong: RenderStrong,
  html: RenderHtml,
  tag: RenderTag,
  image: RenderImage,
  em: RenderEm,
  heading: RenderHeading,
  link: RenderLink,
  paragraph: RenderParagraph,
  blockquote: RenderBlockquote,
  text: RenderText,
  checkbox: RenderCheckbox,
  list: RenderList,
  list_item: RenderListItem,
  task: RenderTask,
  code: RenderCode,
  codespan: RenderCodeSpan,
  table: RenderTable,
  tbody: RenderTableSection,
  thead: RenderTableSection,
  td: RenderTableCell,
  th: RenderTableCell,
  tr: RenderTr,
  generic: RenderGeneric,
} satisfies MarkdownRenderers;
