import { createHighlighterCore } from "shiki/core";
import { createOnigurumaEngine } from "shiki/engine/oniguruma";

export const highlighterPromise = createHighlighterCore({
  engine: createOnigurumaEngine(import("shiki/wasm")),
  themes: [
    import("@shikijs/themes/solarized-light"),
    import("@shikijs/themes/solarized-dark"),
  ],
  langs: [
    import("@shikijs/langs/angular-html"),
    import("@shikijs/langs/angular-ts"),
    import("@shikijs/langs/astro"),
    import("@shikijs/langs/blade"),
    import("@shikijs/langs/c"),
    import("@shikijs/langs/coffee"),
    import("@shikijs/langs/cpp"),
    import("@shikijs/langs/css"),
    import("@shikijs/langs/csv"),
    import("@shikijs/langs/glsl"),
    import("@shikijs/langs/graphql"),
    import("@shikijs/langs/haml"),
    import("@shikijs/langs/handlebars"),
    import("@shikijs/langs/html"),
    import("@shikijs/langs/html-derivative"),
    import("@shikijs/langs/http"),
    import("@shikijs/langs/hurl"),
    import("@shikijs/langs/imba"),
    import("@shikijs/langs/java"),
    import("@shikijs/langs/javascript"),
    import("@shikijs/langs/jinja"),
    import("@shikijs/langs/jison"),
    import("@shikijs/langs/json"),
    import("@shikijs/langs/json5"),
    import("@shikijs/langs/jsonc"),
    import("@shikijs/langs/jsx"),
    import("@shikijs/langs/julia"),
    import("@shikijs/langs/less"),
    import("@shikijs/langs/markdown"),
    import("@shikijs/langs/marko"),
    import("@shikijs/langs/mdc"),
    import("@shikijs/langs/mdx"),
    import("@shikijs/langs/php"),
    import("@shikijs/langs/postcss"),
    import("@shikijs/langs/pug"),
    import("@shikijs/langs/python"),
    import("@shikijs/langs/r"),
    import("@shikijs/langs/regexp"),
    import("@shikijs/langs/sass"),
    import("@shikijs/langs/scss"),
    import("@shikijs/langs/shellscript"),
    import("@shikijs/langs/sql"),
    import("@shikijs/langs/stylus"),
    import("@shikijs/langs/svelte"),
    import("@shikijs/langs/ts-tags"),
    import("@shikijs/langs/tsx"),
    import("@shikijs/langs/typescript"),
    import("@shikijs/langs/vue"),
    import("@shikijs/langs/vue-vine"),
    import("@shikijs/langs/wasm"),
    import("@shikijs/langs/wgsl"),
    import("@shikijs/langs/wit"),
    import("@shikijs/langs/xml"),
    import("@shikijs/langs/yaml"),
  ],
  langAlias: {
    coffeescript: "coffee",
    "c++": "cpp",
    gql: "graphql",
    hbs: "handlebars",
    js: "javascript",
    cjs: "javascript",
    mjs: "javascript",
    jl: "julia",
    md: "markdown",
    jade: "pug",
    py: "python",
    regex: "regexp",
    bash: "shellscript",
    sh: "shellscript",
    shell: "shellscript",
    zsh: "shellscript",
    stl: "stylus",
    lit: "ts-tags",

    ctsx: "tsx",
    mtsx: "tsx",
    typescriptreact: "tsx",
    ts: "typescript",
    cts: "typescript",
    mts: "typescript",
    yml: "yaml",
  },
});
